# Generated by Django 5.1.7 on 2025-03-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(default="author", max_length=255),
            preserve_default=False,
        ),
    ]
