# Generated by Django 5.1.7 on 2025-03-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_userbookrelation_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=3, null=True
            ),
        ),
    ]
