# Generated by Django 5.1.7 on 2025-03-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_book_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbookrelation",
            name="rate",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Ok"),
                    (2, "Fine"),
                    (3, "Good"),
                    (4, "Amazing"),
                    (5, "Incredible"),
                ],
                default=False,
                null=True,
            ),
        ),
    ]
